version: "3.8"

services:
  my-api-serve:
    build: .
    ports:
      - "8082:8082"
    environment:
      RABBITMQ_HOST: rabbitmq
      REDIS_HOST: redis
      POSTGRES_HOST: postgresql
      MONGO_HOST: mongodb
    depends_on:
      - rabbitmq
      - redis
      - postgresql
      - mongodb

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgresql:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

volumes:
  postgres-data:
    driver: local